name: CI and releases
on:
  pull_request:
  push:
    branches: [main]

jobs:
  ci-module:
    uses: relaycorp/shared-workflows/.github/workflows/tfmodule-ci.yml@main
    with:
      terraform_version: 1.5.3

  release:
    needs:
      - ci-module
    uses: relaycorp/shared-workflows/.github/workflows/tfmodule-release.yml@main
